pipeline {
    agent any

    stages {
      stage('Hello') {
          steps {
            echo 'Hello World'
            sh 'pwd'
          }
      }

      stage('Build Image'){
        steps {
           sh '''
              cd helloworld && docker build -t clmkathy/helloworld:JR10 .
              cd ../my_nginx && docker build -t clmkathy/my_nginx:JR10 .
              cd ../tic_tac_toe && docker build -t clmkathy/tic_tac_toe:JR10 .
              docker tag clmkathy/helloworld:JR10 clmkathy/helloworld:latest
              docker tag clmkathy/my_nginx:JR10 clmkathy/my_nginx:latest
              docker tag clmkathy/tic_tac_toe:JR10 clmkathy/tic_tac_toelatest
              docker tag clmkathy/tic_tac_toelatest clmkathy/tic_tac_toe:latest
              docker images
              '''
        }
      }

      stage('Push Image'){
        steps {
         withCredentials([usernamePassword(credentialsId: 'dockerhub_creds', passwordVariable: 'PWD', usernameVariable: 'USR')]) {
                  sh """                        
                    docker login -u $USR -p $PWD
                    for img in clmkathy/helloworld:JR10 clmkathy/helloworld:latest clmkathy/tic_tac_toe:JR10 clmkathy/tic_tac_toe:latest clmkathy/my_nginx:JR10 clmkathy/my_nginx:latest; do docker push \$img; done;
                   """
                }
            }
      }

      stage('Deploy Service') {
         steps {
          sh '''
            docker-compose down
            docker-compose up -d
            docker-compose ps
            '''
         }
      }
    }
}