pipeline {
    agent any

    stages {
      stage('Hello') {
          steps {
          
            echo 'Hello World'
            sh '''
              cd ..
              pwd
            '''
            sh 'cd .. && pwd'
            sh 'pwd'
          }
      }

      stage('Build Image'){
        steps {
           sh '''
              pwd
              cd helloworld && docker build -t clmkathy/helloworld:JR10 .
              cd ../my_nginx && docker build -t clmkathy/my_nginx:JR10 .
              cd ../tic_tac_toe && docker build -t clmkathy/tic_tac_toe:JR10 .
              docker tag clmkathy/helloworld:JR10 clmkathy/helloworld:latest
              docker tag clmkathy/my_nginx:JR10 clmkathy/my_nginx:latest
              docker tag clmkathy/tic_tac_toe:JR10 clmkathy/tic_tac_toe:latest
              docker images
              pwd
              '''
        }
      }

      stage('Push Image'){
        steps {
          sh "pwd"
       
         withCredentials([usernamePassword(credentialsId: 'dockerhub_creds', passwordVariable: 'PWD', usernameVariable: 'USR')]) {
                  sh """                        
                    docker login -u $USR -p $PWD
                    for img in clmkathy/helloworld:JR10 clmkathy/helloworld:latest clmkathy/tic_tac_toe:JR10 clmkathy/tic_tac_toe:latest clmkathy/my_nginx:JR10 clmkathy/my_nginx:latest; do docker push \$img; done;
                   """
                }

                   sh 'ls -la'
            }
      }

      stage('Deploy Service') {
         steps {
          sh '''            
            docker compose down
            docker compose up -d
            docker compose ps
            '''
         }
      }
    }

    // post {
    //    always {
    //     // One or more steps need to be included within each condition's block.
    //     echo "Start clean workspace"
    //     cleanWs()
    //     echo "Workspace cleaned"
    //     sh 'ls -la'
    //     sh 'pwd'
    //     // Failure because test.txt had already been cleaned up
    //     // sh 'cat test.txt'
    //   }
    //   success {
    //     echo "In post-success"
    //   }
    //   failure {
    //     echo "In post-failure"
    //   }
    // }
}